security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false


    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider

      # Login: only runs on POST /api/login
      json_login:
        check_path: /api/login
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

      # Normal requests: looks for an Authorization: Bearer … token
      jwt: ~

    main:
      lazy: true
      provider: app_user_provider

      # No auth on main, we're serving frontend
      security: false


  access_control:
    # public endpoints
    - { path: ^/api/login$,    roles: PUBLIC_ACCESS }
    - { path: ^/api/register$, roles: PUBLIC_ACCESS }

    # everything else under /api needs a valid token
    - { path: ^/api,           roles: IS_AUTHENTICATED_FULLY }
